Repository rsksmart/devportal, pull requests merged in 2020-05, with the labels that each got.

#293 Security chain
  _includes/nav-page-menu.html
  _rsk/node/contribute/linux.md
  _rsk/node/contribute/macos.md
  _rsk/node/contribute/verify.md
  _rsk/node/security-chain.md
  tutorials/ethereum-devs/geth-attach-local-node-mac.md
  tutorials/ethereum-devs/setup-truffle-oz.md
  tutorials/truffle-boxes/pet-shop-box.md
Labels: do NOT merge

#297 docs: update block explorer URLs to remove trailing slash
  develop/apps/wallets/metamask.md
  tutorials/ethereum-devs/remix-and-metamask-with-rsk-testnet.md
Labels: question

#314 newsletter sign up form
  assets/css/styles.css
  assets/js/main.js
  newsletter/index.md
Labels: enhancement
