Repository rsksmart/devportal, pull requests merged in 2020-09, with the labels that each got.

#422 rwallet guides + store links
  assets/css/rwallet-guide.css
  assets/img/rwallet/android/1.png
  assets/img/rwallet/android/2.png
  assets/img/rwallet/android/3.png
  assets/img/rwallet/android/4.png
  assets/img/rwallet/android/5.png
  assets/img/rwallet/android/6.png
  assets/img/rwallet/android/7.png
  assets/img/rwallet/android/8.png
  assets/img/rwallet/android/android.png
  assets/img/rwallet/android/android.svg
  assets/img/rwallet/android/google-play-badge.png
  assets/img/rwallet/bg.png
  assets/img/rwallet/green_shape.png
  assets/img/rwallet/ios/1.png
  assets/img/rwallet/ios/2.png
  assets/img/rwallet/ios/3.png
  assets/img/rwallet/ios/4.png
  assets/img/rwallet/ios/5.png
  assets/img/rwallet/ios/6.png
  assets/img/rwallet/ios/7.png
  assets/img/rwallet/ios/8.png
  assets/img/rwallet/ios/app-store-badge.svg
  assets/img/rwallet/ios/mac-os-logo.svg
  assets/img/rwallet/iovlabs.png
  assets/img/rwallet/logo.png
  assets/img/rwallet/logos.svg
  assets/img/rwallet/powered_by_iov.svg
  wallet/rwallet/android.html
  wallet/rwallet/index.md
  wallet/rwallet/ios.html
Labels: ready for review

#425 feat: rns mainnet
  _includes/nav-page-menu.html
  rif/marketplace/dev-setup.md
  rif/marketplace/guide/getting-started.md
  rif/marketplace/guide/index.md
  rif/marketplace/guide/intro.md
  rif/marketplace/guide/setup.md
  rif/marketplace/index.md
  rif/marketplace/mainnet.md
  rif/marketplace/testnet.md
  rif/rns/testnet.md
Labels: ready to merge

#441 Add try rns section
  rif/rns/try-rns.md
Labels: rns
